services:
  builder:
    image: node:24-bullseye-slim
    container_name: "builder"
    working_dir: /app
    environment:
      SERVICE: ${SERVICE:-App}
      BASE_URL: ${BASE_PATH:-/}
    volumes:
      - ../../:/app
    command: >
      sh -lc "
        if [ ! -d node_modules ]; then npm ci; fi &&
        npm run build:prod &&
        tail -f /dev/null
      "
    networks:
      - nginx

  nginx:
    image: nginx:1.27-alpine
    container_name: "nginx"
    restart: on-failure
    depends_on:
      - builder
    environment:
      # Which service folder under ./dist to serve
      SERVICE: ${SERVICE:-App}
      # Where the app is mounted in the URL (must match what you built with BASE_URL)
      # Use "/" for root, or "/myapp/" (with leading & trailing slash) for a sub-path
      BASE_PATH: ${BASE_PATH:-/}
    ports:
      # Host port : container port (nginx listens on 80)
      - ${APP_PORT:-10000}:80
    volumes:
      - ../../dist/:/app:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    networks:
      - nginx

networks:
  nginx:
