apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE}-config-${BUILD_TIMESTAMP}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: "${IMG_TAG}"
data:
  BASE_PATH: ${NGINX_BASE_PATH}
  DEFAULT_SERVICE: ${NGINX_DEFAULT_SERVICE}
  LISTEN_PORT: "${NGINX_PORT}"
  