apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${SERVICE}-helmrelease
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${NGINX_HELM_CHART_VERSION}
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: ${NGINX_HELM_CHART_VERSION}
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: helmrepository
  valuesFrom:
    - kind: ConfigMap
      name: ${SERVICE}-config
      valuesKey: values.yaml