apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-content-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${NGINX_HELM_CHART_STORAGE_CLASS_NAME}
