apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}-service
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: "${IMG_TAG}"
spec:
  selector:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
  ports:
    - protocol: TCP
      port: ${NGINX_PORT}
      targetPort: ${NGINX_PORT}
  type: ClusterIP